### ISSUE TITLE
Adriconf crashes with invalid path

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/br.com.jeanhertel.adriconf#6]
```
INFO: adriconf running on X11
ERROR: Generic Error: boost::filesystem::directory_iterator::construct: Arquivo ou diretório inexistente: "/var/run/host/usr/share/drirc.d/"
```

**Comment by jlHertel** [comment]
I think this is due to the way we are requesting permissions now, as instead of requesting the full `host` permission we are only requesting the necessary directories.
I just pushed a hot-fix to address this. 

Once the build passes, please wait 3 hours for Flatbot to publish it to the main flathub website.

**Comment by jlHertel** [comment]
Hey @nedrichards 
Yesterday I changed some of the permissions of adriconf to make it more restrictive.
One of the changes was replacing `--filesystem=host` to those specific paths:
```
"--filesystem=~/.drirc",
"--filesystem=/etc/drirc:ro",
"--filesystem=/usr/share/drirc.d:ro"
```

Unfortunately now I keep getting an error on the application saying that the path `/usr/share/drirc.d/` doesn't exist. Any idea why this permission didn't worked?
Reading the manual I don't see any restriction in applying such permissions.

**Comment by TingPing** [comment]
You can't have filesystem permissions into `/etc` or `/usr`.

**Comment by jlHertel** [comment]
I reverted adriconf to use the `host` permission. Closing this as the issue has been resolved.
